### ISSUE TITLE
Object(...) is not a function

### ISSUE THREAD

**Issue by ayubUOL** [jrquick17/ng-speed-test#10]
Hi, I've Ionic 3 app with angular 5 installed in it and I installed ng-speed-test. It got installed successfully but when I test the code then error appears. I don't know what I'm missing, need help.
Thank you

![Screenshot 2021-03-16 at 5 08 08 PM](https://user-images.githubusercontent.com/24814955/111306652-4cf21e00-867a-11eb-8461-cb767ef8601c.png)
![Screenshot 2021-03-16 at 5 08 35 PM](https://user-images.githubusercontent.com/24814955/111306663-4fed0e80-867a-11eb-818a-bfee4598231b.png)

**Comment by jrquick17** [comment]
@ayubUOL Could be the version of rxjs you're using. Can you share your package.json?

**Comment by ayubUOL** [comment]
Thank you for response. My rxjs version is 5.5.11

`{
  "name": "amazing-deli",
  "version": "0.0.1",
  "author": "Ionic Framework",
  "homepage": "http://ionicframework.com/",
  "private": true,
  "scripts": {
    "start": "ionic-app-scripts serve",
    "clean": "ionic-app-scripts clean",
    "build": "ionic-app-scripts build",
    "lint": "ionic-app-scripts lint"
  },
  "dependencies": {
    "@angular/animations": "5.2.11",
    "@angular/common": "5.2.11",
    "@angular/compiler": "5.2.11",
    "@angular/compiler-cli": "5.2.11",
    "@angular/core": "5.2.11",
    "@angular/forms": "5.2.11",
    "@angular/http": "5.2.11",
    "@angular/platform-browser": "5.2.11",
    "@angular/platform-browser-dynamic": "5.2.11",
    "@ionic-native/badge": "^4.20.0",
    "@ionic-native/barcode-scanner": "^4.20.0",
    "@ionic-native/bluetooth-serial": "^4.20.0",
    "@ionic-native/camera": "^4.20.0",
    "@ionic-native/core": "~4.11.0",
    "@ionic-native/date-picker": "^4.20.0",
    "@ionic-native/device": "^4.20.0",
    "@ionic-native/file": "^4.20.0",
    "@ionic-native/geolocation": "^4.20.0",
    "@ionic-native/in-app-browser": "^4.20.0",
    "@ionic-native/keyboard": "^4.20.0",
    "@ionic-native/native-audio": "^4.20.0",
    "@ionic-native/native-storage": "^4.20.0",
    "@ionic-native/network": "^4.20.0",
    "@ionic-native/onesignal": "^4.20.0",
    "@ionic-native/printer": "^4.20.0",
    "@ionic-native/screen-orientation": "^4.20.0",
    "@ionic-native/splash-screen": "^4.20.0",
    "@ionic-native/star-prnt": "^4.20.0",
    "@ionic-native/status-bar": "^4.20.0",
    "@ionic-native/stripe": "^4.20.0",
    "@ionic-native/vibration": "^4.20.0",
    "@ionic/storage": "2.1.3",
    "@netflix/nerror": "^1.1.3",
    "@ng-bootstrap/ng-bootstrap": "2.0.0",
    "@ng-idle/core": "^2.0.0-beta.15",
    "@ng-idle/keepalive": "^2.0.0-beta.15",
    "@types/hammerjs": "^2.0.36",
    "@types/jquery": "3.3.31",
    "animate.css": "^3.7.2",
    "chart.js": "^2.9.4",
    "cordova-ios": "^5.1.0",
    "cordova-plugin-add-swift-support": "^2.0.2",
    "cordova-plugin-badge": "^0.8.8",
    "cordova-plugin-bluetooth-serial": "^0.4.7",
    "cordova-plugin-camera": "^4.1.0",
    "cordova-plugin-datepicker": "^0.9.3",
    "cordova-plugin-device": "^2.0.3",
    "cordova-plugin-file": "^6.0.2",
    "cordova-plugin-geolocation": "^4.0.2",
    "cordova-plugin-ionic-keyboard": "^2.2.0",
    "cordova-plugin-ionic-webview": "^5.0.0",
    "cordova-plugin-nativeaudio": "^3.0.9",
    "cordova-plugin-nativestorage": "^2.3.2",
    "cordova-plugin-printer": "^0.7.3",
    "cordova-plugin-screen-orientation": "^3.0.2",
    "cordova-plugin-splashscreen": "^5.0.4",
    "cordova-plugin-starprnt": "^2.2.0",
    "cordova-plugin-statusbar": "^2.4.3",
    "cordova-plugin-stripe": "^1.5.3",
    "cordova-plugin-vibration": "^3.1.1",
    "cordova-plugin-whitelist": "^1.3.4",
    "cordova-plugin-zip": "^3.1.0",
    "cordova-res": "^0.15.1",
    "es6-promise-plugin": "^4.2.2",
    "fast-glob": "^3.2.4",
    "hammerjs": "^2.0.8",
    "ionic-angular": "3.9.2",
    "ionic-long-press": "^2.0.2",
    "ionicons": "3.0.0",
    "jquery": "3.3.1",
    "moment": "^2.29.1",
    "ng-connection-service": "^1.0.4",
    "ng-speed-test": "^2.1.1",
    "ngx-order-pipe": "^2.1.1",
    "phonegap-plugin-barcodescanner": "^8.1.0",
    "read-chunk": "^3.2.0",
    "rxjs": "5.5.11",
    "sw-toolbox": "3.6.0",
    "ts-md5": "^1.2.7",
    "zone.js": "0.8.26"
  },
  "devDependencies": {
    "@ionic/app-scripts": "^3.2.4",
    "@ionic/lab": "2.0.18",
    "cordova-android": "^9.0.0",
    "cordova-browser": "^6.0.0",
    "cordova-plugin-app-launcher": "git+https://github.com/nchutchind/cordova-plugin-app-launcher.git",
    "cordova-plugin-decimal-keyboard": "git+https://github.com/mrchandoo/cordova-plugin-decimal-keyboard.git",
    "cordova-plugin-inappbrowser": "^4.0.0",
    "cordova-plugin-nativestorage": "^2.3.2",
    "onesignal-cordova-plugin": "^2.11.1",
    "typescript": "~2.6.2"
  },
  "description": "An Ionic project",
  "cordova": {
    "plugins": {
      "phonegap-plugin-barcodescanner": {
        "ANDROID_SUPPORT_V4_VERSION": "27.+"
      },
      "cordova-plugin-datepicker": {},
      "cordova-plugin-whitelist": {},
      "cordova-plugin-device": {},
      "cordova-plugin-vibration": {},
      "cordova-plugin-nativeaudio": {},
      "cordova-plugin-printer": {},
      "cordova-plugin-badge": {},
      "cordova-plugin-zip": {},
      "cordova-plugin-decimal-keyboard": {},
      "cordova-plugin-stripe": {},
      "cordova-plugin-geolocation": {
        "GEOLOCATION_USAGE_DESCRIPTION": "To locate you"
      },
      "cordova-plugin-bluetooth-serial": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-screen-orientation": {},
      "cordova-plugin-camera": {
        "ANDROID_SUPPORT_V4_VERSION": "27.+"
      },
      "cordova-plugin-starprnt": {},
      "cordova-plugin-file": {},
      "cordova-plugin-ionic-keyboard": {},
      "cordova-plugin-app-launcher": {},
      "cordova-plugin-statusbar": {},
      "cordova-plugin-inappbrowser": {},
      "cordova-plugin-nativestorage": {},
      "cordova-plugin-ionic-webview": {},
      "onesignal-cordova-plugin": {}
    },
    "platforms": [
      "browser",
      "android"
    ]
  }
}
`

**Comment by jrquick17** [comment]
You will need to update your version of rxjs to 6^
