### ISSUE TITLE
Throws error when internet is not available(offline mode)

### ISSUE THREAD

**Issue by sksaifuddin** [jrquick17/ng-speed-test#5]
When the system is offline or there is no internet available it throws error **ng-speed-test: Error downloading file.**

It will be great if it first check internet availability and for no internet it should return speed 0. It will be also good to have if as soon as system get online the function gets triggered and it returns speed.

**Comment by jrquick17** [comment]
This has been added in [v1.3.0](https://github.com/jrquick17/ng-speed-test/commit/bd90af59b2503507f0fbf8f1bac0f90b1e126fb2). 

Thanks!
