### ISSUE TITLE
File size unit is wrong

### ISSUE THREAD

**Issue by mwmw7** [jrquick17/ng-speed-test#59]
// https://raw.githubusercontent.com/jrquick17/ng-speed-test/02c59e4afde67c35a5ba74014b91d44b33c0b3fe/demo/src/assets/500kb.jpg
    // 500kb      // 408949 kb

I think 408949 bytes is right

README and comments have wrong unit

![image](https://user-images.githubusercontent.com/1140031/216262657-f4088ee4-015b-4314-bc9f-2f300cd24ba2.png)

**Comment by jrquick17** [comment]
This is a known discrepancy which we do call out in the README. 
![dgns](https://user-images.githubusercontent.com/7435558/218506002-28ae961c-661e-4dab-9260-a2b472634422.PNG)

The code does use the exact byte size so the speed checks out of the box should be accurate. Ideally the image would be exactly 500kb but not a priority at the moment. If you have images that match then feel free to submit a pull request.
