### ISSUE TITLE
Megabytes per second, or Megabits?

### ISSUE THREAD

**Issue by Napkin41** [jrquick17/ng-speed-test#7]
Just wanted to say, after using this package and comparing to speedtest.net, it looks like in your documentation .GetX is in bits, not bytes, which is the standard.

I would recommend updating your documentation to clarify this.

e.g.
"getMbps() - Get the current internet speed in M**bps** (mega**bits** per second)."

Edit: I hope this isn't read in an angry tone, I like this package, thank you for it!

**Comment by jrquick17** [comment]
Thank you @Napkin41! Good point. I will update the documentation.

**Comment by jrquick17** [comment]
Fixed in v2.1.1
