### ISSUE TITLE
Speed returned is not accurate

### ISSUE THREAD

**Issue by irastee** [jrquick17/ng-speed-test#8]
I am getting 3.2 Mbps via the plugin but using https://fast.com/# I am getting 10Mbps

**Comment by jrquick17** [comment]
@irastee Can you provide code samples? Depending upon configuration the speed will be more or less accurate.

**Comment by irastee** [comment]
Hi,
Please find the attached code

[speedtest.txt](https://github.com/jrquick17/ng-speed-test/files/5690675/speedtest.txt)

**Comment by jrquick17** [comment]
Nonissue. When compared with different speed test services this one closely resembles them. There can be a variety of reasons for the speed tests to not always match (algorithm, which server, # of iterations, size of file, etc). 

The code provided uses the default configuration which means the internet speed is calculated using a request from GitHub servers. So differences in speed could also be attributed to GitHub server response times.

You can further increase the accuracy of the tests by increasing the number of iterations or using your own file at a different server location.
